stages:
  - build
  - test
  - deploy

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t rss-aggregator .

test:
  stage: test
  script:
    - docker run rss-aggregator mvn test